name: Deploy to Cloud Run

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0


    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2  
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}' 

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and Deploy to Cloud Run
      run: |
        gcloud builds submit ./backend --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE }}
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE }} \
          --platform managed \
          --region ${{ secrets.REGION }} \
          --allow-unauthenticated
