name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Build Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/flask-web-app .

      - name: Authenticate to Google Cloud
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo $GCP_SA_KEY | base64 --decode > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project $GCP_PROJECT_ID

      - name: Push Docker image
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/flask-web-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-web-app \
            --image gcr.io/$GCP_PROJECT_ID/flask-web-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated